_wandb:
    value:
        cli_version: 0.23.1
        e:
            oksm3z2xr1vgwll96h8zvmqqv97c5eqe:
                codePath: src\main.py
                codePathLocal: main.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "1024191361024"
                        used: "324087693312"
                email: shangjiufang@gmail.com
                executable: C:\Users\Mark z'j'l\AppData\Local\Programs\Python\Python311\python.exe
                git:
                    commit: a09411c3172e9ada91b30e076170d99b4fefb945
                    remote: git@github.com:FragranceShang/construction-safety-agent.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-5ea3bb27-4370-5f93-e5c4-e046b8beb881
                host: Mark-LAPTOP
                memory:
                    total: "17024741376"
                os: Windows-10-10.0.26200-SP0
                program: F:\大四\模式识别与机器学习\pj\src\main.py
                python: CPython 3.11.3
                root: F:\大四\模式识别与机器学习\pj\src
                startedAt: "2025-12-27T11:59:55.036993Z"
                writerId: oksm3z2xr1vgwll96h8zvmqqv97c5eqe
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 95
                - 105
            "2":
                - 2
                - 1
                - 3
                - 5
                - 11
                - 49
                - 53
                - 75
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.3
            "5": 0.23.1
            "6": 4.57.3
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
memory_type:
    value: vector_rag
model:
    value: deepseek-3.1
top_k:
    value: 5
use_summary:
    value: false
